group_id = "stevegroup"
name = "stevegroup"
is_public = false
admin_public_key = """
-----BEGIN PGP PUBLIC KEY BLOCK-----

xjMEaWwnpxYJKwYBBAHaRw8BAQdAyQlpttWLkdmp1R1wpK8LjEFRXRaKPb2waxba
0rbMpf3NBmxlYWd1ZcKGBBAWCAAuBQJpbCenFiEE+U1h0iG0G8q08Zqk7RJ0bm5J
LJkCGwECHgEBCwEVARYBJwIZAQAKCRDtEnRubkksmQvJAP9mfqie+uTtLW5YgU7V
nsPbbguqBVjTOomTQQCF3OLLdAEAwPuV6x4hSvWP98aOw1FIhyqPVYOEd3HvOIf1
51y3VAjOMwRpbCenFgkrBgEEAdpHDwEBB0ApoNxZOJkNUD5S5hnItQT26CZpCAm2
NhgtIdhVh3wHosLALwQYFggAlwUCaWwnpwIbAhYhBPlNYdIhtBvKtPGapO0SdG5u
SSyZdiAEGRYIAB0FAmlsJ6cWIQQfm8LghXcSKihWK+tRtui7D0Y36QAKCRBRtui7
D0Y36Y8lAQCm+d79TIkaRFbTZGK/2Rof/DCtyt/8B+P8yc1iLGjAJwEAy0Y2EgWC
6cx5c43IIpYUyM0e4ifHLcn6VIWCrppwwAsACgkQ7RJ0bm5JLJl0qgEA1wjVgx/t
VvStYlHNyyE9g9iLvlrlPpy2tabm9h+bPpsA/1DW57dnZxSJzuAXwQGM54scHqgU
tDCNclvirRMy8NwEzjgEaWwnpxIKKwYBBAGXVQEFAQEHQCo4oBASwP2OCCWAqz+K
yUDjo+J+hYT/w8+M+LHtMttBAwEIB8J4BBgWCAAgBQJpbCenAhsMFiEE+U1h0iG0
G8q08Zqk7RJ0bm5JLJkACgkQ7RJ0bm5JLJn1EQD9GaLW6u1/wcLRBfOszBW4no6L
RL4KyUoXJ2wHAfnZMKQBAM4j90QRvOW0ERn/sp+gNTgUWrC2nHFC1I8vogYsbSYM
=iT/u
-----END PGP PUBLIC KEY BLOCK-----"""
registered = false
