group_id = "group8200"
name = "8200"
description = "8200"
is_public = false
admin_public_key = """
-----BEGIN PGP PUBLIC KEY BLOCK-----

xjMEaW7THhYJKwYBBAHaRw8BAQdAoGu+ufGS+10HD0hx0Qnm+dVBCTLwZMwxZCyg
3OBtT9HNBnVzZXIxNcKGBBAWCAAuBQJpbtMeFiEEMalVI7SBqpoT3wGHIfj3REfV
lyYCGwECHgEBCwEVARYBJwIZAQAKCRAh+PdER9WXJhdzAQCn2RbMgN00ODi56A9V
m5Zd4zHkNLyIB1IGNoA5s4tLdwEAx1CS7e2j8+R5h6615/yVJqPi26tIh2Htxhn4
cDCzdgzOMwRpbtMeFgkrBgEEAdpHDwEBB0AtZxhHmgpTgCJcoUVlxFQSLZeyN/Vd
wtvl9wmUUnfYRMLALwQYFggAlwUCaW7THgIbAhYhBDGpVSO0gaqaE98BhyH490RH
1ZcmdiAEGRYIAB0FAmlu0x4WIQSSDlyZk53nJTy4NPczDhb7xh1BkgAKCRAzDhb7
xh1BkoNVAP456DVQbBalw6JmCj7sWnDvkQgM5JZKDO9vyiLi6ImKhQEA8SrBwNKq
Ac8vvo0Qme0uIWOA3Q8h6Gr1zCowtLjd0A0ACgkQIfj3REfVlyb75gD5AY7OHUFC
oyCEDxdsajbTbvt/112iwYFTvhP02B1nz1IA/iqfiDf75baFKAMKUKRTkqbwfRtk
e/Y/V6MgrrwKDSUPzjgEaW7THhIKKwYBBAGXVQEFAQEHQGamkv9AdR4BDpgv/f+4
9KlqiISCZXjb1S7bwii6/QINAwEIB8J4BBgWCAAgBQJpbtMeAhsMFiEEMalVI7SB
qpoT3wGHIfj3REfVlyYACgkQIfj3REfVlybU5wEAj0Jg8hC04bkCE+JMyM3B/5fi
CSdSghHGY3MKzSj2BjgA/0npANFXN02ADsuKxd1uEDeQdYHGWgKEBWQ3Gae3V2oI
=RaXA
-----END PGP PUBLIC KEY BLOCK-----"""
registered = false
